### PR TITLE
Solved Issue: #1

### LINKED ISSUE #1: Making UI better
Make the front-end of the look bit more good

### PR DESCRIPTION
**Pull request by GustavoTxFreitas-zz**
Good afternoon, @samarth-1729!
As we talked, I’ve been working to contribute to your wonderful project. I transformed the design solution I presented into code, using the Bootstrap library.
<hr>
<p align="center">
Small changes have been made that I believe improve the readability of the source code.
<br><br>

</p>
I hope the changes have been made clear, however, if you have any problems, you can contact me!

I recommend using github's web hosting services to make it easier for others to see the project, you can find an official guide by visiting https://pages.github.com/.

Have a great weekend,
Gustavo Teixeira.

### CODE REVIEW

**Comment by samarth-1729** [comment]
Hello, 
Great work!
I want just two minor changes: 
1. Decrease the space around the Text container and send button
2. I would really appreciate it if you could make a success message disappear automatically after some time.

Thank you

**Comment by samarth-1729** [comment]
One more thing to add,
I just noticed that the send button doesn't work on clicking it.
Please look into that.

**Comment by GustavoTxFreitas-zz** [comment]
All done!

**Comment by samarth-1729** [comment]
You have added node modules also while making PR please delete the node modules and push the changes

**Comment by GustavoTxFreitas-zz** [comment]
True, I had forgotten 😅 
Do you think I should change anything else?

**Comment by samarth-1729** [comment]
Hi,
I have tested it, it works fine 
Just one thing that one can send many blank messages, see if you could prevent a user from sending a blank message

**Comment by samarth-1729** [comment]
Great!

**Pull request merged**
